### ISSUE TITLE
Verion 18 up

### ISSUE THREAD

**Issue by heyheyitsdan** [ihrapsa/hassio-addons#2]
HyperHDR 18.0.0.0 has been released can the add be updated to pull the new version?

Thanks

**Comment by ihrapsa** [comment]
Sorry for the late reply, the addon has been updated. Enjoy!
Please let me know of any issues/bugs

Jonah

**Comment by MattWestb** [comment]
Looks working OK and the loading problems with newer HA (endpoint init) is also fixed :-)))

## Great work done !!
